# Generated by Django 5.0.3 on 2024-03-26 11:40

import django.db.models.deletion
import rocks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MountainPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_title', models.CharField(default='пер. ', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=6)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=6)),
                ('height', models.IntegerField()),
                ('level', models.CharField(choices=[('winter', 'winter'), ('spring', 'spring'), ('summer', 'summer'), ('autumn', 'autumn')], max_length=100)),
                ('level_category', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to=rocks.models.MountainPass.user_directory_path, verbose_name='image')),
                ('pass_status', models.CharField(choices=[('new', 'new'), ('pnd', 'pending'), ('acc', 'accepted'), ('rjd', 'rejected')], default='new', max_length=10)),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tourist')),
            ],
        ),
    ]
