# Generated by Django 5.0.3 on 2024-03-28 11:01

import rocks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mountainpass',
            name='image',
            field=models.ImageField(blank=True, upload_to=rocks.models.MountainPass.user_directory_path),
        ),
        migrations.AlterField(
            model_name='mountainpass',
            name='pass_status',
            field=models.CharField(choices=[('новый', 'new'), ('в ожидании', 'pending'), ('подтвержден', 'accepted'), ('отклонен', 'rejected')], default='new', max_length=50),
        ),
    ]
